# Travis CI configuration file for running tests
language: python
branches:
  only:
    - master
python:
  - "2.7"
addons:
  apt:
    packages:
      - nodejs
      - python-demjson
before_install:
  - sudo apt-get update
install:
  - "pip install --allow-all-external -r requirements.txt"
  - "pip install --allow-all-external demjson"
env:
  - MAKE_TARGET=docker.test
  - MAKE_TARGET=test.syntax
  - MAKE_TARGET=test.edx_east_roles
script:
  - make $MAKE_TARGET
