---
#
# edX Configuration
#
# github:     https://github.com/edx/configuration
# wiki:       https://github.com/edx/configuration/wiki
# code style: https://github.com/edx/configuration/wiki/Ansible-Coding-Conventions
# license:    https://github.com/edx/configuration/blob/master/LICENSE.TXT
#
##
# Defaults for role buildbot-worker
#
buildbot_worker_group: buildbot_worker
buildbot_worker_user: buildbot_worker

buildbot_worker_dir: "{{ COMMON_APP_DIR }}/buildbot-worker"
buildbot_worker_venv: "{{ buildbot_worker_dir }}/venv"
buildbot_worker_venv_bin: "{{ buildbot_worker_venv }}/bin"
buildbot_worker_workerdir: "{{ buildbot_worker_dir }}/worker"

buildbot_worker_host: localhost
buildbot_worker_name: worker1
buildbot_worker_pass: somesupersecurepassword
