# requires:
# - oraclejdk
# - elasticsearch
---
- name: Add Elasticsearch apt key.
  apt_key:
    url: http://packages.elasticsearch.org/GPG-KEY-elasticsearch
    state: present

- name: Add Logstash repository.
  apt_repository:
    repo: 'deb http://packages.elasticsearch.org/logstash/2.3/debian stable main'
    state: present

- name: Check if Logstash is already installed.
  stat: path=/etc/init.d/logstash
  register: logstash_installed

- name: Update apt cache if repository just added.
  apt: update_cache=yes
  when: logstash_installed.stat.exists == false

- name: Install Logstash.
  apt: pkg=logstash state=present

- name: Ensure logstash config is in place
  template: src=logstash.conf.j2 dest="/etc/logstash/conf.d/logstash.conf" owner=logstash group=logstash mode=0644
  notify: restart logstash

- name: Ensure logstash has a dir {{ logstash_external_log_dir }} for all stored logs
  file: path={{ logstash_external_log_dir }} owner=logstash group=logstash mode=0755 state=directory

- name: Ensure logstash has a share dir in {{ logstash_app_dir }}
  file: path={{ logstash_app_dir }}/share owner=logstash group=logstash mode=0755 state=directory

- name: Install python requirements
  pip: name={{ item }} state=present
  with_items: "{{ logstash_python_requirements }}"

- name: Checkout logstash rotation scripts
  git: repo={{ logstash_scripts_repo }} dest={{ logstash_app_dir }}/share/logstash-elasticsearch-scripts
  when: LOGSTASH_ROTATE|bool

- name: Setup cron to run rotation
  cron:
    user: root
    name: "Elasticsearch logstash index rotation"
    hour: "{{ logstash_rotate_cron.hour }}"
    minute: "{{ logstash_rotate_cron.minute }}"
    job: "/usr/bin/python {{ logstash_app_dir }}/share/logstash-elasticsearch-scripts/logstash_index_cleaner.py -d {{ LOGSTASH_DAYS_TO_KEEP }} > {{ logstash_log_dir }}/rotation_cron"
  when: LOGSTASH_ROTATE|bool

- name: Setup cron to run rotation
  cron:
    user: root
    name: "Elasticsearch logstash index optimization"
    hour: "{{ logstash_optimize_cron.hour }}"
    minute: "{{ logstash_optimize_cron.minute }}"
    job: "/usr/bin/python {{ logstash_app_dir }}/share/logstash-elasticsearch-scripts/logstash_index_optimize.py -d {{ LOGSTASH_DAYS_TO_KEEP }} > {{ logstash_log_dir }}/optimize_cron"
  when: LOGSTASH_ROTATE|bool

- name: plugins | installing logstash plugins
  command: "sudo /opt/logstash/bin/logstash-plugin install {{ item }}"
  notify: "restart logstash"
  with_items: LOGSTASH_PLUGINS

- name: Ensure Logstash is started and enabled on boot.
  service: "name=logstash state=started enabled=yes"
