---
#
# edX Configuration
#
# github:     https://github.com/edx/configuration
# wiki:       https://github.com/edx/configuration/wiki
# code style: https://github.com/edx/configuration/wiki/Ansible-Coding-Conventions
# license:    https://github.com/edx/configuration/blob/master/LICENSE.TXT
#
##
# Defaults for role buildbot-common
#

buildbot_app_dir: "{{ COMMON_APP_DIR }}/buildbot"
buildbot_venv_dir: "{{ buildbot_app_dir }}/venv"
buildbot_venv_bin: "{{ buildbot_venv_dir }}/bin"