---
#
# edX Configuration
#
# github:     https://github.com/edx/configuration
# wiki:       https://github.com/edx/configuration/wiki
# code style: https://github.com/edx/configuration/wiki/Ansible-Coding-Conventions
# license:    https://github.com/edx/configuration/blob/master/LICENSE.TXT
#
##
# Defaults for role buildbot-master
#
buildbot_master_group: buildbot_master
buildbot_master_user: buildbot_master

buildbot_master_dir: "{{ COMMON_APP_DIR }}/buildbot-master"
buildbot_master_venv: "{{ buildbot_master_dir }}/venv"
buildbot_master_venv_bin: "{{ buildbot_master_venv }}/bin"
buildbot_master_masterdir: "{{ buildbot_master_dir }}/master"
