---
#
# edX Configuration
#
# github:     https://github.com/edx/configuration
# wiki:       https://github.com/edx/configuration/wiki
# code style: https://github.com/edx/configuration/wiki/Ansible-Coding-Conventions
# license:    https://github.com/edx/configuration/blob/master/LICENSE.TXT
#
#
#
# Tasks for role buildbot-worker
#
# Overview:
#
#
# Dependencies:
#   - common
#
#
# Example play:
#
#

- name: create buildbot worker group
  group:
    name: "{{ buildbot_worker_group }}"
    state: present

- name: allow worker group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: "^%{{ buildbot_worker_group }}"
    line: "%{{ buildbot_worker_group }} ALL=(ALL) NOPASSWD: ALL"

- name: add the buildbot worker user to the group
  user:
    name: "{{ buildbot_worker_user }}"
    append: yes
    groups: "{{ buildbot_worker_group }}"

- name: make buildbot-worker directory
  file:
    path: "{{ buildbot_worker_dir }}"
    state: directory
    mode: 0755
    owner: "{{ buildbot_worker_user }}"
    group: "{{ buildbot_worker_group }}"

- name: create virtualenv for buildbot-worker
  command: virtualenv --clear "{{ buildbot_worker_venv }}"
  become: yes
  become_user: "{{ buildbot_worker_user }}"

- name: install buildbot-worker
  pip:
    name: 'buildbot-worker'
    virtualenv: "{{ buildbot_worker_venv }}"
  become: yes
  become_user: "{{ buildbot_worker_user }}"

- name: create buildbot worker
  command: "{{ buildbot_worker_venv_bin }}/buildbot-worker create-worker \
    {{ buildbot_worker_workerdir }} {{ buildbot_worker_host }} \
    {{ buildbot_worker_name }} {{ buildbot_worker_pass }}"
  become: yes
  become_user: "{{ buildbot_worker_user }}"

- name: start buildbot worker
  command: "{{ buildbot_worker_venv_bin }}/buildbot-worker start \
    {{ buildbot_worker_workerdir }}"
  become: yes
  become_user: "{{ buildbot_worker_user }}"
