---
#
# edX Configuration
#
# github:     https://github.com/edx/configuration
# wiki:       https://github.com/edx/configuration/wiki
# code style: https://github.com/edx/configuration/wiki/Ansible-Coding-Conventions
# license:    https://github.com/edx/configuration/blob/master/LICENSE.TXT
#
#
#
# Tasks for role buildbot_worker
#
# Overview:
#
#
# Dependencies:
#   - common
#   - jscover
#
#
# Example play:
#
#

- name: Create buildbot_worker group
  group:
    name: "{{ buildbot_worker_group }}"
    state: present

- name: Allow buildbot_worker group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: "^%{{ buildbot_worker_group }}"
    line: "%{{ buildbot_worker_group }} ALL=(ALL) NOPASSWD: ALL"

- name: Add the buildbot_worker user to the group
  user:
    name: "{{ buildbot_worker_user }}"
    append: yes
    groups: "{{ buildbot_worker_group }}"

- name: Make buildbot_worker directory
  file:
    path: "{{ buildbot_worker_dir }}"
    state: directory
    mode: 0755
    owner: "{{ buildbot_worker_user }}"
    group: "{{ buildbot_worker_group }}"

# TODO: Create task for stopping workers
# Currently, you can only reprovision while workers are stopped. To
# reprovision, first either manually stop all workers or run 'vagrant halt'.

- name: Create virtualenv for buildbot_worker
  command: virtualenv --clear "{{ buildbot_worker_venv }}"
  become: yes
  become_user: "{{ buildbot_worker_user }}"

- name: Install buildbot-worker
  pip:
    name: 'buildbot-worker'
    virtualenv: "{{ buildbot_worker_venv }}"
  become: yes
  become_user: "{{ buildbot_worker_user }}"

- name: Create worker1
  command: "{{ buildbot_worker_venv_bin }}/buildbot-worker create-worker \
    {{ buildbot_worker_worker1dir }} {{ buildbot_worker1_host }} \
    {{ buildbot_worker1_name }} {{ buildbot_worker1_pass }}"
  become: yes
  become_user: "{{ buildbot_worker_user }}"

- name: Start worker1
  command: "{{ buildbot_worker_venv_bin }}/buildbot-worker start \
    {{ buildbot_worker_worker1dir }}"
  become: yes
  become_user: "{{ buildbot_worker_user }}"

- name: Create worker2
  command: "{{ buildbot_worker_venv_bin }}/buildbot-worker create-worker \
    {{ buildbot_worker_worker2dir }} {{ buildbot_worker2_host }} \
    {{ buildbot_worker2_name }} {{ buildbot_worker2_pass }}"
  become: yes
  become_user: "{{ buildbot_worker_user }}"

# The -l flag is necessary to get npm to work properly. It can be added more
# elegantly in Ansible 2.2 by using become_flags
- name: Start worker2
  command: "su {{ buildbot_worker_user }} -l -c \
    \"{{ buildbot_worker_venv_bin }}/buildbot-worker start \
    {{ buildbot_worker_worker2dir }}\""
  become: yes
  environment:
    JSCOVER_JAR: "/usr/local/bin/JSCover-all-{{ jscover_version }}.jar"

- name: Install configuration requirements
  apt:
    name: "{{ item }}"
    update_cache: yes
  with_items:
    - nodejs
    - python-demjson
  become: yes

- name: Install edx-platform requirements
  apt:
    name: "{{ item }}"
    update_cache: yes
  with_items:
    - bundler
    - firefox=28.0+build2-0ubuntu2
  become: yes
