- name: Configure instance(s)
  hosts: all
  become: True
  gather_facts: True
  vars:
    EDXAPP_SETTINGS: devstack
    migrate_db: 'yes'
    devstack: true
    disable_edx_services: true
    mongo_enable_journal: false
    EDXAPP_NO_PREREQ_INSTALL: 0
    COMMON_SSH_PASSWORD_AUTH: "yes"
    EDXAPP_LMS_BASE: 127.0.0.1:8000
    EDXAPP_OAUTH_ENFORCE_SECURE: false
    EDXAPP_LMS_BASE_SCHEME: http
    edxapp_use_custom_theme: true
    edxapp_theme_name: 'lagunita'
    edxapp_theme_source_repo: 'https://github.com/Stanford-Online/lagunita-theme.git'
    ENABLE_ELK: true
    configuration_version: 'merge-upstream-2016-12-15'
    edx_platform_version: 'merge-upstream-2016-12-15'
    ECOMMERCE_DJANGO_SETTINGS_MODULE: "ecommerce.settings.devstack"
    # When provisioning your devstack, we apply security updates
    COMMON_SECURITY_UPDATES: true
    SECURITY_UPGRADE_ON_ANSIBLE: true
    MONGO_AUTH: false
  vars_files:
    - roles/edxapp/vars/devstack.yml
  roles:
    - common
    - vhost
    - edx_ansible
    - mysql
    - edxlocal
    - memcache
    - mongo
    - role: rabbitmq
      rabbitmq_ip: 127.0.0.1
    - edxapp
    - oraclejdk
    - elasticsearch
    - forum
    - ecommerce
    - role: ecomworker
      ECOMMERCE_WORKER_BROKER_HOST: 127.0.0.1
    - role: notifier
      NOTIFIER_DIGEST_TASK_INTERVAL: "5"
    - browsers
    - browsermob-proxy
    - local_dev
    - demo
    - oauth_client_setup
    - role: logstash
      when: ENABLE_ELK
    - role: nginx
      nginx_sites:
        - kibana
      when: ENABLE_ELK
    - role: kibana
      when: ENABLE_ELK
    - role: filebeat
      when: ENABLE_ELK
